# Generated by Django 2.1.1 on 2018-10-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_testimonial',
            name='company',
            field=models.CharField(default='null', max_length=128),
            preserve_default=False,
        ),
    ]
