# Generated by Django 2.1.1 on 2018-10-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0002_model_testimonial_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_jobnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128)),
            ],
        ),
    ]
